'use strict';

export {default as SettingNavBar} from './SettingNavBar.jsx';
export {default as BoardSettingPage} from './BoardSettingPage.jsx';
export {default as AgingSettingPage} from './aging/AgingSettingPage.jsx';
export {default as CardIdSettingPage} from './cardId/CardIdSettingPage.jsx';
export {default as ClassOfServiceSettingPage} from './classOfService/ClassOfServiceSettingPage.jsx';
export {default as CustomFieldConfigSettingPage} from './customFieldConfig/CustomFieldConfigSettingPage.jsx';
export {default as GeneralSettingPage} from './general/GeneralSettingPage.jsx';
export {default as ImportExportSettingPage} from './importExport/ImportExportSettingPage.jsx';
export {default as ImpedimentTypeSettingPage} from './impedimentType/ImpedimentTypeSettingPage.jsx';
export {default as ItemTypeSettingPage} from './itemType/ItemTypeSettingPage.jsx';
export {default as ItemSizeSettingPage} from './itemSize/ItemSizeSettingPage.jsx';
export {default as PermissionSettingPage} from './permission/PermissionSettingPage.jsx';
export {default as PreferenceSettingPage} from './preference/PreferenceSettingPage.jsx';
export {default as ProjectSettingPage} from './project/ProjectSettingPage.jsx';
export {default as PrioritySettingPage} from './priority/PrioritySettingPage.jsx';
export {default as MetricSettingPage} from './metric/MetricSettingPage.jsx';
export {default as TagCategorySettingPage} from './tagCategory/TagCategorySettingPage.jsx';
export {default as TagSettingPage} from './tag/TagSettingPage.jsx';
export {default as TaskTypeSettingPage} from './taskType/TaskTypeSettingPage.jsx';
export {default as TrackerIntegrationSettingPage} from './trackerIntegration/TrackerIntegrationSettingPage.jsx';
export {default as TrackerIntegrationSettingDoc} from './trackerIntegration/TrackerIntegrationSettingDoc.jsx';
export {default as RatingTypeSettingPage} from './ratingType/RatingTypeSettingPage.jsx';
