FROM mongo:3.2.0
MAINTAINER KaoBravo <aa@aa.com>

RUN mkdir -p /data/app
RUN mkdir -p /data/app/static
RUN mkdir -p /data/app/static/images
RUN mkdir -p /data/app/static/attachments
RUN mkdir -p /data/app/tmp
RUN mkdir -p /data/app/tmp/restify
RUN mkdir -p /data/app/tmp/export
RUN mkdir -p /data/app/logs
RUN mkdir -p /data/app/config

CMD [ "mongo", "--break-mongo" ]

